name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: [26.1.1, 25.3.2, 24.3.4, 23.2.5, 22.3.4.16, 21.3.8.21]
    container:
      image: erlang:${{ matrix.otp }}

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit
